# Generated by Django 6.0.2 on 2026-02-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('capacidade', models.PositiveIntegerField()),
                ('ocupacao_atual', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
