# Generated by Django 6.0.2 on 2026-02-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidadesaude',
            options={'verbose_name': 'Unidade de Saúde', 'verbose_name_plural': 'Unidades de Saúde'},
        ),
        migrations.RemoveField(
            model_name='unidadesaude',
            name='capacidade',
        ),
        migrations.RemoveField(
            model_name='unidadesaude',
            name='ocupacao_atual',
        ),
        migrations.AddField(
            model_name='unidadesaude',
            name='pacientes_em_espera',
            field=models.IntegerField(default=0, verbose_name='Pacientes em Espera'),
        ),
        migrations.AddField(
            model_name='unidadesaude',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='unidadesaude',
            name='endereco',
            field=models.CharField(max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='unidadesaude',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome da Unidade'),
        ),
    ]
